feed/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostUpdateView, PostDeleteView
from feed import views

app_name = 'feed'

urlpatterns = [
    path('', PostListView.as_view(), name='posts-list'),
    path('<int:id>/detail/', PostDetailView.as_view(), name='posts-detail'),
    path('<int:id>/update/', PostUpdateView.as_view(), name='posts-update'),
    path('<int:id>/delete/', PostDeleteView.as_view(), name='posts-delete'),
    path('like/', views.post_like, name='like'),
    path('', views.post_list, name='list'),
    path('search/', views.post_search, name='post_search'),
]

my_social_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('^accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls', namespace='profiles')),
    path('', include('feed.urls', namespace='posts')),
    path('posts/', include('feed.urls', namespace='posts')),
    path('post/', include('comments.urls', namespace='comments')),
    path('profiles/', include('actions.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users import views
from .views import (
    ProfileListView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
)

app_name = 'users'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profiles-list'),
    path('<int:id>/detail/', ProfileDetailView.as_view(), name='profiles-detail'),
    path('<int:id>/delete/', ProfileDeleteView.as_view(), name='profiles-delete'),
    path('<int:id>/update/', ProfileUpdateView.as_view(), name='profiles-update'),
    path('profile/follow/', views.user_follow, name='user_follow'),
]

users/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import User

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]

STATUS_CHOICES = [
    ('Married', 'Married'),
    ('Single', 'Single')
]

PROFESSION_CHOICES = [
    ('Student or Learning', 'Student or Learning'),
    ('Junior Developer', 'Junior Developer'),
    ('Middle Developer', 'Middle Developer'),
    ('Senior Developer', 'Senior Developer'),
    ('Developer', 'Developer'),
    ('Manager', 'Manager'),
    ('Instructor or Teacher', 'Instructor or Teacher'),
    ('Intern', 'Intern'),
    ('Digital Marketer', 'Digital Marketer'),
    ('Data Scientist', 'Data Scientist'),
]

DEGREE_CHOICES = [
    ('IT', 'Information Technologies'),
    ('Bussiness Managment', 'Bussiness Managment'),
    ('Digital Marketing', 'Digital Marketing'),
    ('Computer Science', 'Computer Science'),
    ('Civil Engineering', 'Civil Engineering'),
    ('AI', 'Artificial & Inteligence'),
    ('Other', 'Other')
]


# PROFILE MODEL MANAGER
class ProfileManager(models.Manager):
    def get_auth_profile(self, profile, user, *args, **kwargs):
        return get_object_or_404(self, pk=profile, user=user)

    def check_auth_profile(self, user, *args, **kwargs):
        try:
            obj = self.get(user=user)
            if obj:
                return obj
        except Profile.DoesNotExist:
            return None


# PROFILE MODEL
class Profile(models.Model):
    user = models.OneToOneField(User, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=80, default='username')
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=10, default=1, choices=GENDER_CHOICES)
    status = models.CharField(max_length=10, default=1, choices=STATUS_CHOICES)
    website = models.URLField(max_length=283, blank=True, null=True)
    company = models.CharField(max_length=120)
    profession = models.CharField(max_length=120, default='Web Developer', choices=PROFESSION_CHOICES)
    location = models.CharField(max_length=100, default='Bishkek')
    skills = models.CharField(max_length=120, choices=None, default='bomj')
    bio = models.TextField(blank=True, default='Hello pacany..!')
    image = models.ImageField(upload_to='profile_pics/', default='default.jpg', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    objects = ProfileManager()

    def __str__(self, *args, **kwargs):
        return self.name

    def get_absolute_url(self, *args, **kwargs):
        return reverse('profiles:profiles-detail', kwargs={'id': self.pk})

    def get_update_url(self, *args, **kwargs):
        return reverse('profiles:profiles-update', kwargs={'id': self.pk})

    def get_delete_url(self, *args, **kwargs):
        return reverse('profiles:profiles-delete', kwargs={'id': self.pk})

users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]

STATUS_CHOICES = [
    ('Married', 'Married'),
    ('Single', 'Single')
]

PROFESSION_CHOICES = [
    ('Student or Learning', 'Student or Learning'),
    ('Junior Developer', 'Junior Developer'),
    ('Senior Developer', 'Senior Developer'),
    ('Developer', 'Developer'),
    ('Manager', 'Manager'),
    ('Instructor or Teacher', 'Instructor or Teacher'),
    ('Intern', 'Intern'),
    ('ussiness Man', 'Bussiness Man'),
    ('Digital Marketer', 'Digital Marketer'),
    ('Data Scientist', 'Data Scientist'),
    ('Other', 'Other')
]

DEGREE_CHOICES = [
    ('IT', 'Information Technologies'),
    ('Bussiness Managment', 'Bussiness Managment'),
    ('Digital Marketing', 'Digital Marketing'),
    ('Computer Science', 'Computer Science'),
    ('Civil Engineering', 'Civil Engineering'),
    ('AI', 'Artificial & Inteligence'),
    ('Other', 'Other')
]


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField()


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Name'})
    )

    age = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Age'})
    )

    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control form-control-lg', })
    )

    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        widget=forms.Select(
            attrs={'class': 'form-control form-control-lg', })
    )

    website = forms.URLField(
        required=False,
        widget=forms.URLInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Website'})
    )

    company = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Company'})
    )

    profession = forms.ChoiceField(
        choices=PROFESSION_CHOICES,
        widget=forms.Select(
            attrs={'class': 'form-control form-control-lg'})
    )

    location = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Country'})
    )

    skills = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Skills'})
    )

    bio = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Country', 'rows': 4})
    )

    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(
            attrs={'class': 'form-control form-control-lg', })
    )

    class Meta:
        model = Profile
        fields = (
            'name', 'age', 'gender', 'status', 'website', 'company',
            'profession', 'location', 'skills', 'bio', 'image',)

    def clean_age(self, *args, **kwargs):
        age = self.cleaned_data.get('age')
        if age > 50:
            raise forms.ValidationError('Age must be below 50 years!')
        elif age < 18:
            raise forms.ValidationError('Age must be at least 18 years!')
        else:
            return age

users/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from actions.utils import create_action
from actions.models import Contact
from .forms import *


class RegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'account/signup.html'
    success_url = '/dev/accounts/login'

    def form_valid(self, form):
        messages.success(self.request, 'User has been registered successfully!')
        return super(RegisterView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['title'] = 'Register'
        return context


class LoginView(View):
    form = LoginForm
    template_name = 'account/login.html'
    context = {}

    def get(self, request, *args, **kwargs):
        form = self.form()
        self.context['title'] = 'Login'
        self.context['form'] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get('user_obj')
            login(request, user)
            messages.success(request, 'Yay! You just logged in!')
            return redirect(reverse('pages:dashboard-view'))
        self.context['title'] = 'Login'
        self.context['form'] = form
        return render(request, self.template_name, self.context)


class LogoutView(View):
    @staticmethod
    def get(request, *args, **kwargs):
        logout(request)
        messages.success(request, 'You has been logged out successfully!')
        return redirect(reverse('accounts:accounts-login'))


class ProfileObjectMixin(object):
    model = Profile
    lookup = 'id'

    def get_object(self, *args, **kwargs):
        return self.model.objects.get_auth_profile(
            self.kwargs.get(self.lookup),
            self.request.user
        )


class CheckAuthProfileMixin(object):
    model = Profile

    def get_object(self, *args, **kwargs):
        obj = self.model.objects.check_auth_profile(self.request.user)
        if not obj is None:
            return obj
        else:
            return None


class ProfileListView(ListView):
    queryset = Profile.objects.all()
    context_object_name = 'profiles'
    template_name = 'profiles/profiles_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileListView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Profiles'
        return context


class ProfileDetailView(DetailView):
    queryset = Profile.objects.all()
    context_object_name = 'profile'
    template_name = 'profiles/profile_detail.html'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Profile, pk=self.kwargs.get('id'))

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        context['title'] = self.get_object().name
        return context


class ProfileUpdateView(LoginRequiredMixin, ProfileObjectMixin, UpdateView):
    queryset = Profile.objects.all()
    context_object_name = 'profile'
    template_name = 'profiles/profile_update.html'
    form_class = ProfileForm

    def get_context_data(self, *args, **kwargs):
        if self.get_object():
            context = super(ProfileUpdateView, self).get_context_data(*args, **kwargs)
            context['title'] = 'Update Profile'
            return context

    def get_success_url(self, *args, **kwargs):
        messages.success(self.request, 'Profile has been updated successfully!')
        return reverse(
            'profiles:profiles-detail', kwargs={'id': self.get_object().pk}
        )


class ProfileDeleteView(LoginRequiredMixin, ProfileObjectMixin, DeleteView):
    queryset = Profile.objects.all()
    context_object_name = 'profile'
    template_name = 'profiles/profile_delete.html'

    def get_context_data(self, *args, **kwargs):
        if self.get_object():
            context = super(ProfileDeleteView, self).get_context_data(*args, **kwargs)
            context['title'] = 'Delete Profile'
            return context

    def get_success_url(self, *args, **kwargs):
        messages.success(self.request, 'Profile has been deleted successfully!')
        return reverse('profiles:profiles-list')


@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')

    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except Profile.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})

users/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'posts:posts-list' %}">VSE POSTY</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="">HZGRAM<span class="sr-only">(current)</span></a>
            </li>

                  {% if user.is_authenticated  %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profiles:profiles-list'%}{{ user.id }}/detail">TVOI PROFILE</a>
                            </li>
                {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    VOITI

                    <div>
                        {% if messages %}
                            <div>
                                <strong>Messages:</strong>
                                <ul>
                                    {% for message in messages %}
                                        <li>{{message}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>


                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a href="{% url 'account_email' %}">Change E-mail</a>
                            <div class="dropdown-divider"></div>
                            ><a href="{% url 'account_logout' %}">Sign Out</a>
                        {% else %}
                            <a href="{% url 'account_login' %}">Sign In</a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'account_signup' %}">Sign Up</a>
                        {% endif %}
                    </div>

            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a tabindex="-5"> Welcome {{ user.username }} !!!  </a >
                {% endif %}
            </li>

        </ul>
            <form action="{% url 'feed:post_search' %}" class="form-inline my-2 my-lg-0" method='POST' >
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_form">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Poisk po postam </button>
            </form>
    </div>
</nav>
{% block content %}
{% endblock %}

{% block extra_body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
       });
  </script>

</body>
</html>