feed/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostUpdateView, PostDeleteView
from feed import views

app_name = 'feed'

urlpatterns = [
    path('', PostListView.as_view(), name='posts-list'),
    path('<int:id>/detail/', PostDetailView.as_view(), name='posts-detail'),
    path('<int:id>/update/', PostUpdateView.as_view(), name='posts-update'),
    path('<int:id>/delete/', PostDeleteView.as_view(), name='posts-delete'),
    path('like/', views.post_like, name='like'),
    path('', views.post_list, name='list'),
    path('search/', views.post_search, name='post_search'),
]

my_social_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('^accounts/', include('allauth.urls')),
    path('accounts/profile/', include('users.urls', namespace='profiles')),
    path('', include('feed.urls', namespace='posts')),
    path('posts/', include('feed.urls', namespace='posts')),
    path('post/', include('comments.urls', namespace='comments')),
    path('profiles/', include('actions.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users import views
from .views import (
    ProfileListView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
)

app_name = 'users'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profiles-list'),
    path('<int:id>/detail/', ProfileDetailView.as_view(), name='profiles-detail'),
    path('<int:id>/delete/', ProfileDeleteView.as_view(), name='profiles-delete'),
    path('<int:id>/update/', ProfileUpdateView.as_view(), name='profiles-update'),
    path('profile/follow/', views.user_follow, name='user_follow'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse

from feed.models import Post


class CommentManager(models.Manager):
    def get_comment(self, p_id, c_id, user):
        return get_object_or_404(self, post=p_id, pk=c_id, owner=user)


class Comment(models.Model):
    text = models.TextField(default="awesome!")
    post = models.ForeignKey(Post, default=1, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    objects = CommentManager()

    def __str__(self, *args, **kwargs):
        return self.text

    def get_delete_url(self, *args, **kwargs):
        return reverse(
            'comments:comments-delete',
            kwargs={'post_id': self.post.pk, 'comment_id': self.pk}
        )

    def get_update_url(self, *args, **kwargs):
        return reverse(
            'comments:comments-update',
            kwargs={'post_id': self.post.pk, 'comment_id': self.pk}
        )

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.conf import settings
import redis
from django.contrib.contenttypes.models import ContentType

r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)


class PostManager(models.Manager):
    def get_posts(self, *args, **kwargs):
        return self.all()

    def get_post(self, post_id, *args, **kwargs):
        return get_object_or_404(self, id=post_id)

    def get_user_posts(self, owner, *args, **kwargs):
        return self.filter(owner=owner)

    def get_user_post(self, post_id, user, *args, **kwargs):
        return get_object_or_404(self, pk=post_id, owner=user)


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, default=1, on_delete=models.CASCADE, null=True)
    users_like = models.ManyToManyField(User, related_name='images_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    objects = PostManager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self, *args, **kwargs):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return reverse('posts:posts-detail', kwargs={'id': self.pk})

    def get_delete_url(self, *args, **kwargs):
        return reverse('posts:posts-delete', kwargs={'id': self.pk})

    def get_update_url(self, *args, **kwargs):
        return reverse('posts:posts-update', kwargs={'id': self.pk})

    def get_comment_create_url(self, *args, **kwargs):
        return reverse('comments:comments-create', kwargs={'id': self.pk})

    @property
    def post_total_views(self):
        post = get_object_or_404(Post, id=self.id)
        total_views = r.incr('post:{}:views'.format(post.id))
        return total_views

feed/forms.py
from django import forms
from .models import Post


# class SearchForm(forms.Form):
#     query = forms.CharField()


class PostModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Title'})
    )

    description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Description', 'rows': 3})
    )

    image = forms.ImageField()

    class Meta:
        model = Post
        fields = ('title', 'description', 'image')

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get('title')
        if not title.strip():
            raise forms.ValidationError('Invalid title!')
        else:
            return title

    def clean_description(self, *args, **kwargs):
        description = self.cleaned_data.get('description')
        if not description.strip():
            raise forms.ValidationError('Invalid description!')
        else:
            return description

feed/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from actions.utils import create_action
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import TrigramSimilarity

from .models import Post
from .forms import PostModelForm


class PostListView(CreateView):
    model = Post
    form = PostModelForm
    template_name = 'post_list.html'
    context = {}

    def get(self, request, *args, **kwargs):
        qs = self.model.objects.get_posts()
        form = self.form()
        self.context['title'] = 'Posts'
        self.context['posts'] = qs
        self.context['form'] = form
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = self.request.user
            instance.save()
            messages.success(request, 'Post has been added to feed!')
            return redirect('posts:posts-list')
        messages.error(request, 'Oop! Enter valid details!')
        return reverse('posts:posts-list')


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    context_object_name = 'post'
    lookup = 'id'
    template_name = 'post_detail.html'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Post, pk=self.kwargs.get(self.lookup))

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Post Detail'
        return context


class PostUpdateView(LoginRequiredMixin, UpdateView):
    queryset = Post.objects.all()
    form_class = PostModelForm
    context_object_name = 'post'
    template_name = 'post_update.html'
    lookup = 'id'

    def get_object(self, *args, **kwargs):
        return Post.objects.get_user_post(
            self.kwargs.get(self.lookup),
            self.request.user
        )

    def get_context_data(self, *args, **kwargs):
        context = super(PostUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Post Update'
        return context

    def get_success_url(self, *args, **kwargs):
        messages.success(self.request, 'Post has been updated successfully!')
        return reverse('posts:posts-detail', kwargs={'id': self.kwargs.get(self.lookup)})

    def image_update(self, request, pk, template_name):
        post = get_object_or_404(Post, pk=pk)
        form = self.form_class(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.save()
            return redirect('posts:posts-detail')
        return render(request, template_name, {'form': form})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    queryset = Post.objects.all()
    context_object_name = 'post'
    template_name = 'post_delete.html'
    lookup = 'id'

    def get_object(self, *args, **kwargs):
        return Post.objects.get_user_post(
            self.kwargs.get(self.lookup),
            self.request.user
        )

    def get_context_data(self, *args, **kwargs):
        context = super(PostDeleteView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Post Delete'
        return context

    def get_success_url(self, *args, **kwargs):
        messages.success(self.request, 'Post has been deleted!')
        return reverse('posts:posts-list')


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
                create_action(request.user, 'likes', post)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ok'})


@login_required
def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        posts = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'list_ajax.html',
                      {'section': 'posts', 'posts': posts})
    return render(request,
                  'list.html',
                  {'section': 'posts', 'posts': posts})


def post_search(request):
    query = request.POST.get('search_form')
    results = []
    if query:
        results = Post.objects.annotate(similarity=TrigramSimilarity('title', query)). \
            filter(similarity__gt=0.05).order_by('-similarity')
    return render(request, 'post_search.html', {'query': query, 'results': results})

feed/templates/list.html
{% extends "base.html" %}

{% block title %}POSTS NAH!{% endblock %}

{% block content %}
  <h1>Posts nahuy!</h1>
  <div id="post-list">
    {% include "list_ajax.html" %}
  </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

feed/templates/list_ajax.html
{% load thumbnail %}

{% for post in posts %}
  <div class="image">
    <a href="{{ post.get_absolute_url }}">
      {% thumbnail post.image "300x300" crop="100%" as pm %}
        <a href="{{ post.get_absolute_url }}">
          <img src="{{ pm.url }}">
        </a>
      {% endthumbnail %}
    </a>
    <div class="info">
      <a href="{{ post.get_absolute_url }}" class="title">
        {{ post.title }}
      </a>
    </div>
  </div>
{% endfor %}

feed/templates/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">Cre</h3>

</div>
{% endblock content %}

feed/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="post-delete">
  <h3 class="page-heading">Delete Post</h3>
  <div class="card">
    <div class="card-header">
      <h5>Are you sure? You wanna delete this post?</h5>
    </div>
    <div class="card-body">
      <h4 class="card-title">{{post.title}}</h4>
      <p class="card-text">{{post.description}}</p>
      <form action="" method="POST"> {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{{post.get_absolute_url}}" type="button" class="btn btn-dark">No</a>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

feed/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}
<div class="post-detail">
  <h3 class="page-heading">Post Detail</h3>
  <div class="card">
    <div class="card-header text-center">
      <h4 class="card-title m-0">{{post.title}}</h4>
    </div>
    <div class="card-body text-center">
      <div class="card-left">
            <span class="count">
                {{ post.post_total_views }} view{{ post.post_total_views|pluralize }}
            </span>
        <p class="card-text">{{post.description}}</p>
        <p class="card-text">Author: {{post.owner}}</p>
        <p class="card-text">Created At: {{post.created_at}}</p>
        {% if post.image %}

            {% thumbnail post.image "1200" as big %}
                {% thumbnail post.image "500x350" crop="center" as small %}
                    <a href="{{ big.url }}" title="norm posmotri!"><img src="{{ small.url }}"></a>
                {% endthumbnail %}
            {% endthumbnail %}

            {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                <div class="image-info">
                    <div>
                        <span class="count">
                         <span class="total">{{ total_likes }}</span>
                         like{{ total_likes|pluralize }}
                        </span>
                        <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}unlike{% else %}like{% endif %}" class="like button">
                            {% if request.user not in users_like %}
                                Like
                            {% else %}
                                Unlike
                            {% endif %}
                        </a>
                    </div>
                </div>
                <div class="image-likes">
                    {% for user in post.users_like.all %}
                        <div>
                            <img src="{{ post.profile.image.url }}">
                            <p>{{ user.first_name }}</p>
                        </div>
                    {% empty %}
                        Nobody likes this image yet.
                    {% endfor %}
                </div>
            {% endwith %}

        {% endif %}
      </div>
      <br>
      <form enctype="multipart/form-data" action="" class="">
        {% if user.is_authenticated %}
        <a href="{{post.get_comment_create_url}}" type="button" class="btn btn-dark">Comment</a>
        {% endif %}
        {% if user.is_authenticated and post.owner == user %}
        <a href="{{post.get_update_url}}" type="button" class="btn btn-info">Edit</a>
        <a href="{{post.get_delete_url}}" type="submit" class="btn btn-danger">Delete</a>
        {% endif %}
      </form>
    </div>
    {% if post.comment_set.all %}
    <div class="card-footer">
      <div class="container">
        <h5 class="m-0">Comments</h5>
        <hr>
        {% for comment in post.comment_set.all %}
        <div class="mb-2 d-flex">
          <div>
            <span class="">{{comment.text}}</span><br>
            <small>{{comment.owner}}</small>
          </div>
          {% if comment.owner == user %}
          <form action="" class="">
            <a href="{{comment.get_update_url}}" class="btn btn-sm btn-outline-dark">Edit</a>
            <a href="{{comment.get_delete_url}}" class="btn btn-sm btn-danger">Delete</a>
          </form>
          {% endif %}
        </div>
        <hr>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "posts:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok') {
          let previous_action = $('a.like').data('action')

          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');

          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          let previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'unlike' ? previous_likes - 1 : previous_likes + 1);
        }
      }
    );
  });
{% endblock %}

feed/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block content %}
<div class="post-list">
  <header class="page-header d-flex">
    <h3 class="page-heading">Posts Feed</h3>
    {% if user.is_authenticated %}
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modelId">
      New Post!
    </button>
    {% endif %}
  </header>
  <hr>
  {% if not posts.exists %}
  <p class="lead text-muted">No posts added yet..</p>
  {% else %}
  {% for post in posts %}
  <div class="card card-posts my-2">
    <div class="card-body d-flex">
      <div class="card-left">
        <a href="{{post.get_absolute_url}}"><p class="lead m-0">{{post.title}}</p></a>
            Author: <a class="" href="{% url 'profiles:profiles-list'%}{{post.owner.id}}/detail" >{{post.owner}}</a>
        {% if post.image %}
            {% thumbnail post.image "300x200" crop="center" as im %}
            <a href="{{post.get_absolute_url}}"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a>
            {% endthumbnail %}
        {% endif %}
      </div>
      <div class="card-right">

            {% with total_likes=post.users_like.count users_like=post.users_like.all %}
                <div class="image-info">
                    <div>
                        <span class="count">
                         <span class="total">{{ total_likes }}</span>
                         like{{ total_likes|pluralize }}
                        </span>
                        <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}unlike{% else %}like{% endif %}" class="like button">
                            {% if request.user not in users_like %}
                                Like
                            {% else %}
                                Unlike
                            {% endif %}
                        </a>
                    </div>
                </div>
            {% endwith %}


        <span class="count">
            {{ post.post_total_views }} view{{ post.post_total_views|pluralize }}
        </span>
      </div>

    </div>
  </div>
  {% endfor %}
  {% endif %}


  <!-- Modal -->
  <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
          <div class="modal-body">
            {{ form|crispy }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "users:user_follow" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          $('this.like').data('action', previous_action == 'like' ? 'unlike' : 'like');

          $('this.like').text(parseInt(previous_action) == 'like' ? 'Unlike' : 'Like');

          var previous_likes = parseInt($('span.count .total').text());

          $('span.count .total').text(previous_action == 'unlike' ? parseInt(previous_likes) - 1 : parseInt(previous_likes) + 1);
          console.log(previous_likes, previous_action)
        }
      }
    );
  });
{% endblock %}

feed/templates/post_search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.description|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "feed:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
{#        <form action="." method="get">#}
{#            {{ form.as_p }}#}
{#            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">ISKAT</button>#}
{#        </form>#}
    {% endif %}
{% endblock %}

feed/templates/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block content %}
<div class="post-update">
  <h3 class="page-heading">Update Post</h3>
  <hr>
  <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-lg btn-success">Update</button>
    <a href="{{post.get_absolute_url}}" class="btn btn-lg btn-dark">Discard</a>
  </form>
</div>
{% endblock content %}